# Generated by Django 4.0.3 on 2022-03-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eshop_products_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%D', verbose_name='تصویر')),
                ('active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('visit_count', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('categories', models.ManyToManyField(blank=True, to='eshop_products_category.productcategory', verbose_name='دسته بندی ها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
