# Generated by Django 4.0.3 on 2022-03-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%M', verbose_name='تصویر'),
        ),
    ]
