# Generated by Django 4.0.3 on 2022-03-27 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Author',
            new_name='author',
        ),
    ]
