# Generated by Django 4.0.3 on 2022-03-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان سایت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل پشتیبانی')),
                ('phone', models.CharField(max_length=11, verbose_name='تلفن پشتیبانی')),
                ('addr', models.TextField(verbose_name='آدرس فروشگاه')),
            ],
        ),
    ]
