# Generated by Django 4.0.3 on 2022-03-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='logo',
            field=models.ImageField(null=True, upload_to='logo', verbose_name='لوگوی سایت'),
        ),
    ]
