# Generated by Django 4.0.3 on 2022-03-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0002_setting_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'تنظیم', 'verbose_name_plural': 'تنظیمات'},
        ),
    ]
