# Generated by Django 4.0.3 on 2022-03-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('description', models.CharField(max_length=400, verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='slider/%M', verbose_name='عکس')),
                ('link', models.CharField(max_length=120, verbose_name='لینک')),
            ],
        ),
    ]
